### ISSUE TITLE
JenaJSONLDSerializer does not implement JSONLDSerializer

### ISSUE THREAD

**Issue by wikier** [jsonld-java/jsonld-java#6]
On the current code JSONLDSerializer and JenaJSONLDSerializer does not have the same methods. so instead of:

 JSONLDSerializer serializer = new JenaJSONLDSerializer();

You should use:

 JenaJSONLDSerializer serializer = new JenaJSONLDSerializer();

That's not a big deal, but it's a bad practice on API design according the Façade pattern.
